// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-csTDKjwWTvojLDUL2JhUKktsCy3dqGg',
    appId: '1:964023590272:web:d9b0d7f89573eb850a7565',
    messagingSenderId: '964023590272',
    projectId: 'my-cctracker',
    authDomain: 'my-cctracker.firebaseapp.com',
    storageBucket: 'my-cctracker.appspot.com',
    measurementId: 'G-0QGHJWHP48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8psWCeiiQCTTzCwWXE4ozfDaFu_HzA6Y',
    appId: '1:964023590272:android:6f86cfb9d8b973b30a7565',
    messagingSenderId: '964023590272',
    projectId: 'my-cctracker',
    storageBucket: 'my-cctracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3vVxmT_oyI65fypc0oY49AFG3OYYE7d8',
    appId: '1:964023590272:ios:18ce4dcd25213d3d0a7565',
    messagingSenderId: '964023590272',
    projectId: 'my-cctracker',
    storageBucket: 'my-cctracker.appspot.com',
    iosClientId: '964023590272-ggrjb4g9ugtp2f82kvdt3g5c4fih4nkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ccTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3vVxmT_oyI65fypc0oY49AFG3OYYE7d8',
    appId: '1:964023590272:ios:18ce4dcd25213d3d0a7565',
    messagingSenderId: '964023590272',
    projectId: 'my-cctracker',
    storageBucket: 'my-cctracker.appspot.com',
    iosClientId: '964023590272-ggrjb4g9ugtp2f82kvdt3g5c4fih4nkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ccTracker',
  );
}
